# conda env create -f environment.yml
name: jupyterlab-cell-lock
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab>=4.3.0
  - nodejs=22
  - pytest
  - pytest-check-links
  - pytest-jupyter>=0.6.0
  - python=3
  - twine
  - pip:
    - build==1.3.0
    - pyproject-hooks==1.2.0
